name: build

on:
  push:
    branches: [ master ]
    paths: [ '**.java', '.github/workflows/build.yml' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout badges branch
      uses: actions/checkout@v2
      with:
        ref: badges
        path: badges

    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package -Pcoverage

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        badges-directory: badges
        generate-branches-badge: true

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branches = ${{ steps.jacoco.outputs.branches }}"

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/

    - name: Commit and push
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd badges
        if [[ `git status --porcelain *.svg` ]]; then
          git config --global user.name 'Vincent A. Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git add *.svg
          git commit -m "Autogenerated JaCoCo coverage badge" *.svg
          git push
        fi

#    - name: Create pull request
#      if: ${{ github.event_name == 'push' }}
#      uses: peter-evans/create-pull-request@v3.10.0
#      with:
#        title: "Autogenerated Jacoco Coverage Badge"
#        body: > 
#          Autogenerated Jacoco coverage badge, generated by 
#          the [jacoco-badge-generator](https://github.com/cicirello/jacoco-badge-generator) 
#          GitHub action.  Automated pull-request generated by 
#          [create-pull-request](https://github.com/peter-evans/create-pull-request) 
#          GitHub action.
#        commit-message: "Autogenerated Jacoco Coverage Badge"
#        author: Vincent A Cicirello <cicirello@users.noreply.github.com>
#        committer: Vincent A Cicirello <cicirello@users.noreply.github.com>
#        branch: create-pull-request/badge
#        delete-branch: true
#        labels: |
#          automated

